export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDERT_SUCCESS";
export const PLACE_ORDER_FAIL = "PLACE_ORDER_FAIL";

export const LIST_ORDER_REQUEST = "LIST_ORDER_REQUEST";
export const LIST_ORDER_SUCCESS = "LIST_ORDERT_SUCCESS";
export const LIST_ORDER_FAIL = "LIST_ORDER_FAIL";